const ITEM_LIST_REQUEST= 'ITEM_LIST_REQUEST'
const ITEM_LIST_SUCCESS= 'ITEM_LIST_SUCCESS'
const ITEM_LIST_FAIL= 'ITEM_LIST_FAIL'

export const ITEM_DETAILS_REQUEST= 'ITEM_DETAILS_REQUEST'
export const ITEM_DETAILS_SUCCESS= 'ITEM_DETAILS_SUCCESS'
export const ITEM_DETAILS_FAIL= 'ITEM_DETAILS_FAIL'

export {ITEM_LIST_SUCCESS, ITEM_LIST_FAIL, ITEM_LIST_REQUEST}
