export const CREATE_ORDER_REQUEST= 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS= 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL= 'CREATE_ORDER_FAIL'
export const CREATE_ORDER_RESET= 'CREATE_ORDER_RESET'

export const ORDER_DETAILS_REQUEST= 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS= 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL= 'ORDER_DETAILS_FAIL'

export const ORDER_HISTORY_REQUEST= 'ORDER_HISTORY_REQUEST'
export const ORDER_HISTORY_SUCCESS= 'ORDER_HISTORY_SUCCESS'
export const ORDER_HISTORY_FAIL= 'ORDER_HISTORY_FAIL'

export const PAYMENT_REQUEST= 'PAYMENT_REQUEST'
export const PAYMENT_SUCCESS= 'PAYMENT_SUCCESS'
export const PAYMENT_FAIL= 'PAYMENT_FAIL'